"""
Provenance test for the bundled DA/ID forecast price CSVs.

The example forecast series (used by the illustrative example's imperfect-
foresight scenario S4) are generated by scripts/generate_example_forecasts.py
from the realized price CSVs. This test guarantees the committed forecast CSVs
stay reproducible from that generator, so their origin is verifiable in-repo.

Reproduction is exact only to floating-point precision (the random draws are
bit-stable, but sigma scales with a pandas .mean() that rounds at machine
epsilon differently across library versions), hence the generator's CHECK_TOL.
"""

import importlib.util
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).parent.parent
GEN_PATH = REPO_ROOT / "scripts" / "generate_example_forecasts.py"


def _load_generator():
    spec = importlib.util.spec_from_file_location("generate_example_forecasts", GEN_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_bundled_forecasts_match_generator():
    gen = _load_generator()
    forecasts = gen.build_forecasts()

    for mk, _, out_rel in gen.MARKETS:
        expected = pd.read_csv(
            gen.PRICES_DIR / out_rel, parse_dates=["time"], index_col="time"
        )["price"]
        got = forecasts[mk]
        assert got.index.equals(expected.index), f"{out_rel}: index mismatch"
        maxdiff = float((got.reindex(expected.index) - expected).abs().max())
        assert maxdiff <= gen.CHECK_TOL, f"{out_rel}: maxdiff={maxdiff:.3e} > {gen.CHECK_TOL:.0e}"
